###############################################
## /deployment/linux-base-config-pulumi.yml  ##
###############################################
#
# Backward-compatible wrapper for legacy callers.
# Use /deployment/base-config-pulumi.yml directly.

---
- import_playbook: base-config-pulumi.yml
