name: Deploy Proxmox Prod (Pulumi)

on:
  workflow_dispatch:

jobs:
  deploy-proxmox-prod:
    name: Deploy Proxmox Prod
    runs-on: self-hosted
    container:
      image: ghcr.io/thadigus/turner-services-infrastructure:devcontainer
      options: --network host
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive

      - name: Pulumi Up (production)
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_BACKEND_URL: ${{ secrets.PULUMI_BACKEND_URL }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        working-directory: deployment/pulumi-proxmox
        run: ./run-pulumi-up.sh --prod -u
